# Generated by Django 2.1 on 2018-12-05 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom', to_field='id'),
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='id',
            new_name='eid',
        ),
    ]
