# Generated by Django 2.1 on 2018-12-05 01:49

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20181205_0137'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chatroom',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
