# Generated by Django 2.1 on 2018-12-28 21:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20181205_0149'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chatmessage',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
